### GET
GET http://localhost:8080/api/v1/student


### POST
POST http://localhost:8080/api/v1/student
Content-Type: application/json

{
"name": "James",
"dob": "1990-12-13",
"email": "James@hotmail.co.uk"
}

### Delete by ID
DELETE http://localhost:8080/api/v1/student/2


### PUT
PUT http://localhost:8080/api/v1/student/1?name=John&email=john@hotmail.com
Content-Type: application/json

